[config.wallpaper]
command = "awww"
#arguments = ["img", "--transition-type", "center"]
#set = false 

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update &'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

# [templates.fcitx5]
# input_path = '~/.config/matugen/templates/fcitx5-theme.conf'
# output_path = '~/.local/share/fcitx5/themes/Matugen/theme.conf'
# post_hook= 'fcitx5 -r & disown '

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/colors.conf'
post_hook='makoctl reload &'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'killall -SIGUSR1 btop && killall -SIGUSR2 btop &'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/your-theme'
#post_hook = "pkill -USR1 cava"

# [templates.wlogout]
# input_path = '~/.config/matugen/templates/colors.css'
# output_path = '~/.config/wlogout/colors.css'
# [templates.wlogout-recolor]
# input_path = '~/.config/matugen/templates/wlogout/recolor.sh'
# output_path = '~/.config/wlogout/icons/recolor.sh'
# post_hook = 'chmod +x ~/.config/wlogout/icons/recolor.sh && bash ~/.config/wlogout/icons/recolor.sh &'

[templates.gtk3]
input_path ='~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
[templates.gtk4]
input_path ='~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
